DiscordOAuth2/urls.py
from django.urls import path
from .views import *
app_name = "discord"
urlpatterns = [
    path('', LoginView.as_view(), name="verify")

]

api/urls.py
from .views import *
from django.urls import path


urlpatterns = [
    path('login/', LoginAPIView.as_view(), name="login")
]

bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('server.urls')),
    path('', include('redirect.urls')),
    path('api/', include('api.urls')),
    path('mail/', include('mail.urls')),
    path('discord/', include("DiscordOAuth2.urls"))
]
handler404 = 'redirect.views.error_404'
handler500 = 'redirect.views.server_error'

mail/urls.py
from django.urls import path
from .views import *
app_name = "mail"
urlpatterns = [
    path('', MailView.as_view(), name="index"),
    path('id/<str:id1>/<str:id2>',
         ResetPasswordView.as_view(), name="reset_password_form"),
    path('id', ResetPasswordView.as_view(), name="reset_password"),
    path('verify/<str:id>/', VerifyMail.as_view(), name="verify_mail")

]

redirect/urls.py
from django.urls import path
from .views import *
app_name = "redirect"
urlpatterns = [
    path('', index, name="index"),
    path('link', link, name="create_link"),
    path('redirect/<str:id>/', redirect_pg, name="redirect"),
    path('cs', create_link, name="cs"),
    path('r/<str:id>/', redirect_link, name="redirect_link"),
    path('protect/', ProtectLinkView.as_view(), name="protect"),
    path('redirect/show/<str:id>/', showlinks, name="show")
]

server/urls.py
from django.urls import path
from .views import *
app_name = "main"
urlpatterns = [
    path('index', IndexView.as_view(), name="index"),
    path('login', LoginView.as_view(), name="login"),
    path('signed_up',  SignedUpView.as_view(), name="signed_up"),
    path('logged_in', LoggedInView.as_view(), name="logged_in"),
    path('signup', signup, name="signup"),
    path('logout', logout, name="logout"),
    path('a', add, name="add"),
    path('w', withdraw, name="withdraw"),
    path('del', del_account, name="delete_account"),
    path('yourAccount', account, name="account"),
    path("cp", change_pwd, name="change_pwd"),
    path("t_list", transaction_list, name="transaction_list"),
    path("d_list", delete_transaction_history, name="delete_transactions"),
    path("transaction/<str:transaction_id>", transaction, name="transaction"),
    path("link_d", LinkDiscordView.as_view(), name="link_discord"),
    path("unlink_d", UnlinkDiscordView.as_view(), name="unlink_discord"),
    path("friends", FriendsView.as_view(), name="friends"),
    path("addFriends", AddFriends.as_view(), name="add_friends"),
    path('tMoney', TransferView.as_view(), name="transfer"),
    path('aMail', AddEmailView.as_view(), name="add_email")

]

redirect/models.py
from django.db import models
import uuid
# Create your models here.


class Redirect(models.Model):
    link1 = models.CharField(max_length=10485700)
    unique_id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False)
    link2 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link3 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link4 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link5 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link6 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link7 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link8 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link9 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link10 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)


class RedirectLink(models.Model):
    link = models.CharField(max_length=10485700)
    unique_id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False)
    url = models.CharField(max_length=10485700, null=True)
    url2 = models.CharField(max_length=10485700, null=True)

    def get_url(self, request=None):
        host = request.META['HTTP_HOST']
        self.url = f"http://{host}/r/{self.unique_id}"
        self.save()
        return self.url

    def get_url2(self):
        self.url2 = f"http://djank.herokuapp.com/r/{self.unique_id}"
        self.save()
        return self.url2


class ProtectLink(models.Model):
    link = models.CharField(max_length=10485700)
    password = models.UUIDField(
        default=uuid.uuid4(), null=False, editable=False)

redirect/views.py
from django.core.exceptions import ValidationError
from django.http.response import Http404
from redirect.models import Redirect, RedirectLink, ProtectLink
from django.shortcuts import render, redirect
from django.urls.exceptions import NoReverseMatch
from django.http import HttpResponse
from datetime import datetime
from django.views import View
# Create your views here.


def index(request):
    return redirect('main:login')


def error_404(request, exception):
    error = "PAGE NOT FOUND"
    return render(request, "error.html", context={"error": error})


def server_error(request, exception=None):
    return render(request, "server_error.html", {})


def link(request):
    return render(request, "redirect/main.html")


def redirect_pg(request, id):
    try:
        curent_redirect = Redirect.objects.get(unique_id=id)
    except (Redirect.DoesNotExist, ValidationError, AttributeError, TypeError):
        return HttpResponse("DOES NOT EXIST")
    else:
        link1 = curent_redirect.link1
        link2 = curent_redirect.link2
        link3 = curent_redirect.link3
        link4 = curent_redirect.link4
        link5 = curent_redirect.link5
        link6 = curent_redirect.link6
        link7 = curent_redirect.link7
        link8 = curent_redirect.link8
        link9 = curent_redirect.link9
        link10 = curent_redirect.link10
        link_list = [link1, link2, link3, link4, link5,
                     link6, link7, link8, link9, link10]
        return render(request, "redirect/redirect.html", context={"links": link_list})
        # return redirect(link1)


def create_link(request):
    if request.method == "POST":
        link1 = request.POST.get('link1')
        link2 = request.POST.get('link2')
        link3 = request.POST.get('link3')
        link4 = request.POST.get('link4')
        link5 = request.POST.get('link5')
        link6 = request.POST.get('link6')
        link7 = request.POST.get('link7')
        link8 = request.POST.get('link8')
        link9 = request.POST.get('link9')
        link10 = request.POST.get('link10')
        r_list = [link1, link2, link3, link4, link5,
                  link6, link7, link8, link9, link10]
        host = request.META['HTTP_HOST']
        l1 = RedirectLink.objects.create(link=link1)
        l1.save()
        l2 = RedirectLink.objects.create(link=link2)
        l2.save()
        l3 = RedirectLink.objects.create(link=link3)
        l3.save()
        l4 = RedirectLink.objects.create(link=link4)
        l4.save()
        l5 = RedirectLink.objects.create(link=link5)
        l5.save()
        l6 = RedirectLink.objects.create(link=link6)
        l6.save()
        l7 = RedirectLink.objects.create(link=link7)
        l7.save()
        l8 = RedirectLink.objects.create(link=link8)
        l8.save()
        l9 = RedirectLink.objects.create(link=link9)
        l9.save()
        l10 = RedirectLink.objects.create(link=link10)
        l10.save()
        now = datetime.now()
        date = int(now.strftime("%d"))
        if date >= 22:
            link1 = l1.get_url2()
            link2 = l2.get_url2()
            link3 = l3.get_url2()
            link4 = l4.get_url2()
            link5 = l5.get_url2()
            link6 = l6.get_url2()
            link7 = l7.get_url2()
            link8 = l8.get_url2()
            link9 = l9.get_url2()
            link10 = l10.get_url2()
            print("ok")
        else:
            # Setting alternative url

            link1 = l1.get_url(request=request)
            link2 = l2.get_url(request=request)
            link3 = l3.get_url(request=request)
            link4 = l4.get_url(request=request)
            link5 = l5.get_url(request=request)
            link6 = l6.get_url(request=request)
            link7 = l7.get_url(request=request)
            link8 = l8.get_url(request=request)
            link9 = l9.get_url(request=request)
            link10 = l10.get_url(request=request)

        # print(r_list)
        # link = f"http://{host}/redirect?link1={link1}&link2={link2}&link3={link3}&link4={link4}&link5={link5}&link6={link6}&link7={link7}&link8={link8}&link9={link9}&link10={link10}"
        new_redirect = Redirect.objects.create(
            link1=link1,
            link2=link2,
            link3=link3,
            link4=link4,
            link5=link5,
            link6=link6,
            link7=link7,
            link8=link8,
            link9=link9,
            link10=link10,

        )
        link = f"""http://{host}/redirect/{new_redirect.unique_id}
        <br>
        Show link - http://{host}/redirect/show/{new_redirect.unique_id}
        """
        return render(request, "redirect/link.html", context={"link1": f"http://{host}/redirect/{new_redirect.unique_id}", "link2": f"http://{host}/redirect/show/{new_redirect.unique_id}"})
        # return HttpResponse(link)


def redirect_link(request, id):
    try:
        url = RedirectLink.objects.get(unique_id=id)
    except (AttributeError, RedirectLink.DoesNotExist):
        raise Http404
    else:
        try:
            return redirect(url.link)
        except NoReverseMatch:
            return render(request, "redirect/close.html")


class ProtectLinkView(View):
    @staticmethod
    def get(request):
        return render(request, "redirect/protect.html")

    @staticmethod
    def post(request):
        link = request.POST['link']
        protected = ProtectLink.objects.create(link=link)
        return HttpResponse(f"""
        
        
         Link - http://{request.META['HTTP_HOST']}/protect/{protected.id}
         <br>
         
         Password - {protected.password}""")


# def see_link(request, id):
#     p_link = ProtectLink.objects.get(id=id)
def showlinks(request, id):
    try:
        curent_redirect = Redirect.objects.get(unique_id=id)
    except Redirect.DoesNotExist:
        raise Http404
    else:
        link1 = curent_redirect.link1
        link2 = curent_redirect.link2
        link3 = curent_redirect.link3
        link4 = curent_redirect.link4
        link5 = curent_redirect.link5
        link6 = curent_redirect.link6
        link7 = curent_redirect.link7
        link8 = curent_redirect.link8
        link9 = curent_redirect.link9
        link10 = curent_redirect.link10
        print(f"link10 - {link10}")
        link_list = [link1, link2, link3, link4, link5,
                     link6, link7, link8, link9, link10]
        return render(request, "redirect/show.html", context={"links": link_list})

templates/main/account.html
{% extends 'base.html' %}
{% block title %}Your account{% endblock title %}
{% block body %}
{% load static %}
    
<script src="{% static 'account.js' %}"></script>
{% comment %} ALERT MSGS {% endcomment %}
<div id="non-animation">
<div class=" alert alert-primary" style="display:none;" id="pwd_change_alert">Your password has been changed </div>
<div class=" alert alert-primary" style="display:none;" id="t_list_erase">Your transaction history was deleted </div>
<div class=" alert alert-primary" style="display:none;" id="discord_account_linked">Your discord account was linked</div>
<div class=" alert alert-warning" style="display:none;" id="discord_account_unlinked">Your discord account was unlinked</div>

<div class=" alert alert-danger" style="display:none;" id="format_incorrect">The format of your discord username was incorrect, so it has <b>NOT</b> been linked </div>


{% comment %} ACCOUNT INFO {% endcomment %}
<div id="main" class="shadow-none p-3 mb-5 bg-light rounded">
<h1 class="text">Your account info</h1>
{% if warning %}
<div class="alert alert-warning">{{warning}}</div>
{% endif %}
{% if warning2 %}
<div class="alert alert-warning">{{warning2}}</div>
{% endif %}
<ul>
<h3 class="text text-primary"> Name  - {{user.name}}</h3>
<h3 class="text text-primary"> Balance  - {{user.bank_balance}}</h3>
<h3 class="text text-primary"> Username  - {{user.username}}</h3>
<h3 class="text text-primary"> Email  - {{user.email}}</h3>
<h3 class="text text-primary"> Verified Email  - {{user.email_is_verified}}</h3>

{% if discord_account %}
<h3 class="text text-primary">Discord Username  - {{discord_account.discord_username}}</h3>
<form action="{% url 'main:unlink_discord' %}" method="post">
{% if discord_account.is_verified == True %}
<b><h3 class="text text-success">Discord Account is verified</h3></b>
{% endif %}
{% if discord_account.is_verified == False %}
<h3 class="text text-danger">Discord Account is not verified</h3>
<a href="{% url 'discord:verify' %}" class="btn btn-primary">Verify Discord</a>
<br><br>
{% endif %}
{% csrf_token %}
<input type="submit" value="Unlink Discord" class="btn btn-primary">
</form>
{% else %}
<h3 class="text text-warning">Discord Account is not linked</h3>
<btn class="btn btn-primary" id="link-discord" onclick="link_discord()">Link Discord</btn>

{% endif %}

<br>
<br>
{% if warning %}
<button onclick="email_form()" class="btn btn-primary">
Add email
</button>
{% else %}
<a href="{% url 'main:add_email' %}" class="btn btn-danger">
Unlink email
</a>
{% endif %}
</ul>
<br>

<a class="btn btn-primary" href="/site/index">
Go back
</a>
<a class="btn btn-primary" href="/site/t_list">
See transaction history</a>
<button class="btn btn-dark" onclick="show_pwd_form()">Change Password</button>
</div>


{% comment %} EMAIL FORM {% endcomment %}

<div style="display:none;" id="email_form">
<form action="{% url 'main:add_email' %}" method="post">
{% csrf_token %}
<div class="row g-1 align-items-center">
<div class="col-auto">
<b><h1 class="has-text-weight-bold  has-text-centered is-size-5" for="email">Discord username</h1></b>
<br>
<input class="form-control" type="email" placeholder="Email" name="email" id="email" required>
<br>
</div></div>
<span class="btn btn-success" onclick="back()">Go back</span>
<input id="add_mail_submit" type="submit" value="Add email" class="btn btn-primary">
</form>
</div>


{% comment %} LINK DISCORD {% endcomment %}
<div style="display:none;" id="discord_form">
<form action="{% url 'main:link_discord' %}" method="post">
{% csrf_token %}
<div class="row g-1 align-items-center">
<div class="col-auto">
<b><h1 class="has-text-weight-bold  has-text-centered is-size-5" for="username">Discord username</h1></b>
<br>
<input class="form-control" type="text" placeholder="DiscordUsername#0000" name="username" id="username" required>
<br>
</div></div>
<span class="btn btn-success" onclick="back()">Go back</span>
<input type="submit" value="Link discord" class="btn btn-primary">
</form>
</div>


{% comment %} CHANGE PASSWORD FORM {% endcomment %}
<div style="display:none;" id="pwd_form">
<form action="{% url 'main:change_pwd' %}" method="post">
<div class="row g-1 align-items-center">
<div class="col-auto">
<b><h1 class="has-text-weight-bold  has-text-centered is-size-5" for="password">New password</h1></b>
<br>
<input class="form-control" type="text" placeholder="New Password" name="password" id="password" required>
<br>
<span class="btn btn-danger" onclick="WarningPopup()" value="Change password">Change password </span>
<span class="btn btn-success" onclick="back()">Go back</span>
{% comment %} FINAL CHECK POPUP DIV {% endcomment %}
<div class="modal" id="popUp">
{% csrf_token %}
  <span class="modal-content"  id="myPopup">
  <h1 class="text"><u>Warning</u> ⚠</h1>
  <h2 class="text">Are you sure that you want to change your passoword ?</h2>
  <h4 class="text"> <b>THIS ACTION IS IRREVERSIBLE</b> </h4>
  <br>
  <input type="submit" value="Yes, Change it" name="submit" class="btn btn-primary shadow-lg">
  <br>
  <span onclick="cancel()" class="btn btn-success">No, Go Back</span>
  
  </span> 
</form>

</div>

</div>
</div>
</div>
</div>



<div id="animation" style="display:none;">
<h1 class="text-center" id="animation-text">Trying to add your mail</h1>
<br>
<div class="cssload-loader">
	<div class="cssload-inner cssload-one"></div>
	<div class="cssload-inner cssload-two"></div>
	<div class="cssload-inner cssload-three"></div>
</div>
</div>
{% endblock body %}

templates/main/add_friends.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Add Friends
{% endblock title %}
{% block body %}
{% if user %}
<script src="{% static 'friends.js' %}"></script>

<div id="doesnotexist" class="alert alert-danger" style="display:none;">The account of your friend was not found, so no friend has been added. Kindly, double-check the username (It's case sensitive)</div>
<div id="friend_added" class="alert alert-success" style="display:none;">Your friend has been added, now to can tranfer money to him/her.</div>

<h1>Add Friends</h1>

<form action="{% url 'main:add_friends' %}" method="post">
{% csrf_token %}
<label for="friend">Friend username </label>
<br>
<input class="form-control" type="text" name="friend" placeholder="Friend Username (Usernames are case sensitive)" id="friend" required>
<br>
<input class="btn btn-success"type="submit" value="Add Friend">
&nbsp;
<a href="{% url 'main:index' %}" class="btn btn-primary">Go back</a>
</form>

{% endif %}
{% endblock body %}

templates/main/friends.html
{% extends 'base.html' %}
{% block title %}
Friends
{% endblock title %}
{% block body %}
{% if friends %}
<ul>
    {% for friend in friends %}
<li><h3>{{friend.username}}</h3>
    {% endfor %}
</ul>
<br>
<a href="{% url 'main:add_friends' %}" class="btn btn-success">Add friends</a>
<a href="{% url 'main:index' %}" class="btn btn-primary">Go back</a>

{% else %}
<h1>You don't have any friends yet</h1>
<br>
<a href="{% url 'main:add_friends' %}" class="btn btn-success">Add friends</a>
<a href="{% url 'main:index' %}" class="btn btn-primary">Go back</a>

{% endif %}




{% endblock body %}

templates/main/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock title %}
{% block body %}
{% load static %}
<script src="{% static 'bank.js' %}"></script>
<div id="non-animation">
<div style="display:none;"class="alert alert-danger" id="amount_less">The amount for transfer is less than your bank balance</div>
<div style="display:none;"class="alert alert-success" id="transferred">Your transfer has been completed</div>
<div style="display:none;"class="alert alert-success" id="email_added">Your email was added and we have sent a verification email to your inbox. Please check it to verify your email</div>


<div id="main" style="display:block;">

<div style="display: flex;justify-content: space-between;"class="flex">
<div class="flex-one">
<h1 id="name" class="has-text-weight-medium">Hi {{user.name}}</h1>
</div>
<div style="display:flex; flex-direction:column;" class="flex-3">
<a href="{% url 'main:friends' %}">
<i class="fa-4x fas fa-user-friends" style="text-decoration:none;"></i>
<br>
&nbsp;<span class="text-xl">Friends</span>
</a>
</div>


<div style="display:flex; flex-direction:column;" class="flex-2">
<a href="{% url 'main:account' %}">
<i style="text-decoration:none;" class="fa-4x fas fa-cogs" id="icon"></i>
<br>
&nbsp;<span class="text-xl">Settings</span>
</a>

</div>
</div>


<h2>Your bank balance is <span class="text-success">${{user.bank_balance}}</h2></span>
<br><br>
<button class="btn btn-primary" onclick="show()">
Perform Transactions
</button>
<br><br>
<a class="btn btn-danger" href="{% url 'main:logout'%}">Logout</a>
<br><br>
<button onclick="WarningPopup()" class="btn-danger btn">Delete your account</button>
</div>
{% comment %} Transactions form {% endcomment %}
<div style="display:none;" id="transactions">
<button class="btn btn-primary" onclick="add()">
Add money
</button>
<button class="btn btn-primary" onclick="withdraw()">
Withdraw Money
</button>
<button class="btn btn-primary" onclick="transfer()">
Transfer money to your friends
</button>
<button class="btn btn-primary" onclick="back()">
Go back
</button>
</div>


{% comment %} Add money form {% endcomment %}

<div style="display:none;" id="add">
<form id="add_form" action="{% url 'main:add' %}" method="post">
{% csrf_token %}
<div class="row g-1 align-items-center">
<div class="col-auto">
<b><label class="has-text-weight-bold  has-text-centered is-size-5" for="add_amount">Amount to add</label></b>
<input autocomplete="off"  onkeypress="return noenter()" class="form-control" type="text" placeholder="Amount to add" name="add_amount" id="add_amount" required>
<br>
<span id="add_btn"  class="btn btn-primary" value="Add money">Add money</span>
</div>
</div>

<br>
</form>
<button class="btn btn-primary" onclick="back()">
Go back
</button>
</div>


{% comment %} Withdraw form {% endcomment %}

<div style="display:none;" id="withdraw">
<form id="minus_form" action="{% url 'main:withdraw' %}" method="post">
{% csrf_token %}
<div class="row g-1 align-items-center">
  <div class="col-auto">
<b><label class="has-text-weight-bold  has-text-centered is-size-5" for="withdraw_amount">Amount to withdraw</label></b>
<input autocomplete="off"  onkeypress="return noenter()" class="form-control" type="text" placeholder="Amount to withdraw" name="withdraw_amount" id="withdraw_amount" required>
<br>
<span class="btn btn-primary" id="minus_btn" value="withdraw money">Withdraw money</span>
  </div>
  </div>

<br>

</form>
<button class="btn btn-primary" onclick="back()">
Go back
</button>
</div>


{% comment %} Transfer money form {% endcomment %}
<div style="display:none;" id="transfer">
<form id="transfer_form" action="{% url 'main:transfer' %}" method="post">
{% csrf_token %}
<div class="row g-1 align-items-center">
  <div class="col-auto">
<b><label class="has-text-weight-bold  has-text-centered is-size-5" for="amount">Amount to transfer</label></b>
<input onkeypress="return noenter()" class="form-control" type="text" placeholder="Amount to transfer" name="amount" id="amount" required>
<br> 
<select class="form-select form-select-lg mb-3" name="username" id="username">

{% for friend in friends %}
<option value="{{friend.username}}">{{friend.username}}</option>
{% endfor %}
</select>
<br>
<br>
<button type="submit" class="btn btn-primary" id="transfer_btn" />
Transfer money
</span>
  </div>
  </div>

<br>

</form>
<button class="btn btn-primary" onclick="back()">
Go back
</button>
</div>



{% comment %} DeleteAccount Popup {% endcomment %}
<div class="modal" id="popUp">
<form action="{% url 'main:delete_account' %}" method="post">
{% csrf_token %}
  <span class="modal-content"  id="myPopup">
  <h1 class="text"><u>Warning</u> ⚠</h1>
  <h2 class="text">Are you sure that you want to delete this account</h2>
  <h4 class="text"> <b>THIS ACTION IS IRREVERSIBLE</b> </h4>
  <br>
  <input type="submit" value="Yes, Delete my account" name="submit" class="btn btn-primary shadow-lg">
  <br>
  <span onclick="cancel()" class="btn btn-success">No, Go Back</span>
  </form>
  
  </span> 

</div>

</div>

<div id="animation" style="display:none;">
<h1 class="text-center" id="animation-text">Performing transaction</h1>
<br>
<div class="cssload-loader">
	<div class="cssload-inner cssload-one"></div>
	<div class="cssload-inner cssload-two"></div>
	<div class="cssload-inner cssload-three"></div>
</div>
</div>
{% endblock body %}

templates/main/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}

{% block body %}
{% if error %}
<div  role="alert"class="alert alert-danger">{{error}}</div>
{% endif %}
<form action="{% url 'main:logged_in' %}" method="post">
{% csrf_token %}
<h1>Login</h1>
<div class="row g-1 align-items-center">
  <div class="col-auto">
<label class="has-text-weight-medium  has-text-centered is-size-5" for="username">Username</label>
<input class="form-control" aria-describedby="UsernameHelpInline" type="text" placeholder="Username" name="username" id="username" required>
  </div>
  </div>
</div>
<br>

<div class="row g-10 align-items-center">
  <div class="col-auto">
<label class="has-text-weight-medium  has-text-centered is-size-5" for="password">Password</label>
<input class="form-control" aria-describedby="passwordHelpInline" type="password" placeholder="Password" name="password" id="password" required>
  </div>
  </div>
</div>

<br><input class="btn btn-primary" type="submit" value="Login" required>

</form>
<br>
<a class="btn-link" href="{% url 'main:signup'%}">Don't have an account yet ? <br> Signup</a>
<br>
<br>
<a class="btn-link" href="{% url 'mail:index'%}">Forgot your password ? <br></a>


{% endblock body %}

templates/main/logout.html
{% extends 'base.html' %}   
{% block title %}{{title}}{% endblock title %}
{% block body %}

<h1 id="text" class=" text-info text-center">{{text}}</h1>
<br><br><br>
<div class="cssload-loader">
	<div class="cssload-inner cssload-one"></div>
	<div class="cssload-inner cssload-two"></div>
	<div class="cssload-inner cssload-three"></div>
</div>
<script>
url =window.location.origin 
setTimeout(function(){window.location.replace(`${url}/site/index`)},2300)
window.setInterval(function(){
document.getElementById("text").innerHTML += "."
},650)
</script>
{% endblock body %}

templates/main/redirect.html
<script>
url=window.location.href
console.log(url)
window.setTimeout(window.location.replace("https://django-bank.herokuapp.com/site/index"), 3000)</script>

templates/main/transaction.html
{% extends 'base.html' %}
{% block title %}
Transaction Details
{% endblock title %}
{% block body %}
{% if transaction %}
<h1>Transaction Details</h1>
<ul>
<li><h3 class="text-success">Amount - {{transaction.amount}}</h3>
<li><h3 class="text-success">Type - {{transaction.type}}</h3>
<li><h3 class="text-success">Performed By  - {{user.username}}</h3>
<li><h3 class="text-success">Time - {{transaction.timestamp}} (UTC)</h3>
</ul>
<a href="{% url 'main:transaction_list' %}" class="btn btn-primary">Go Back</a>
{% endif %}
{% endblock body %}

templates/main/transactions.html
{% extends 'base.html' %}
{% block title %}Transaction History{% endblock title %}
{% block body %}
<h1>Transaction History</h1>
<ul>
{% if transactions %}
    {% for transaction in transactions %}
   <li> <a class="text-primary" href="http://{{host}}/site/transaction/{{transaction.transaction_id}}">{{transaction.amount}} - {{transaction.type}} at {{transaction.timestamp}}</a>

    {% endfor %}
</ul>
  <a href="{% url 'main:index' %}" class="btn btn-primary">Go Back</a>
  <br><br><br>
<form action="{% url 'main:delete_transactions' %}" method="post">
<span class="btn btn-danger" onclick="WarningPopup()" value="">Delete transaction history</span>
<div class="modal" id="popUp">
{% csrf_token %}
  <span class="modal-content"  id="myPopup">
  <h1 class="text"><u>Warning</u> ⚠</h1>
  <h2 class="text">Are you sure that you want to change your delete your transaction history ?</h2>
  <h4 class="text"> <b>THIS ACTION IS IRREVERSIBLE</b> </h4>
  <br>
  <input type="submit" value="Yes, Change it" name="submit" class="btn btn-primary shadow-lg">
  <br>
  <span onclick="cancel()" class="btn btn-success">No, Go Back</span> 

</form> 

{% elif no_t %}
<div class="alert alert-danger">{{no_t}}</div>
<a href="{% url 'main:index' %}" class="btn btn-primary">Go Back</a>

{% endif %}



{% endblock body %} 