api/urls.py
from .views import *
from django.urls import path


urlpatterns = [
    path('login/', LoginAPIView.as_view(), name="login")
]

bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('server.urls')),
    path('', include('redirect.urls')),
    path('api/', include('api.urls')),
    path('mail/', include('mail.urls')),
    path('discord/', include("DiscordOAuth2.urls"))
]
handler404 = 'redirect.views.error_404'
handler500 = 'redirect.views.server_error'

redirect/urls.py
from django.urls import path
from .views import *
app_name = "redirect"
urlpatterns = [
    path('', index, name="index"),
    path('link', link, name="create_link"),
    path('redirect/<str:id>/', redirect_pg, name="redirect"),
    path('cs', create_link, name="cs"),
    path('r/<str:id>/', redirect_link, name="redirect_link"),
    path('protect/', ProtectLinkView.as_view(), name="protect"),
    path('redirect/show/<str:id>/', showlinks, name="show")
]

redirect/models.py
from django.db import models
import uuid
# Create your models here.


class Redirect(models.Model):
    link1 = models.CharField(max_length=10485700)
    unique_id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False)
    link2 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link3 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link4 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link5 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link6 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link7 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link8 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link9 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)
    link10 = models.CharField(
        max_length=10485700, editable=True, null=True, default=None)


class RedirectLink(models.Model):
    link = models.CharField(max_length=10485700)
    unique_id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False)
    url = models.CharField(max_length=10485700, null=True)
    url2 = models.CharField(max_length=10485700, null=True)

    def get_url(self, request=None):
        host = request.META['HTTP_HOST']
        self.url = f"http://{host}/r/{self.unique_id}"
        self.save()
        return self.url

    def get_url2(self):
        self.url2 = f"http://djank.herokuapp.com/r/{self.unique_id}"
        self.save()
        return self.url2


class ProtectLink(models.Model):
    link = models.CharField(max_length=10485700)
    password = models.UUIDField(
        default=uuid.uuid4(), null=False, editable=False)

redirect/views.py
from django.core.exceptions import ValidationError
from django.http.response import Http404
from redirect.models import Redirect, RedirectLink, ProtectLink
from django.shortcuts import render, redirect
from django.urls.exceptions import NoReverseMatch
from django.http import HttpResponse
from datetime import datetime
from django.views import View
# Create your views here.


def index(request):
    return redirect('main:login')


def error_404(request, exception):
    error = "PAGE NOT FOUND"
    return render(request, "error.html", context={"error": error})


def server_error(request, exception=None):
    return render(request, "server_error.html", {})


def link(request):
    return render(request, "redirect/main.html")


def redirect_pg(request, id):
    try:
        curent_redirect = Redirect.objects.get(unique_id=id)
    except (Redirect.DoesNotExist, ValidationError, AttributeError, TypeError):
        return HttpResponse("DOES NOT EXIST")
    else:
        link1 = curent_redirect.link1
        link2 = curent_redirect.link2
        link3 = curent_redirect.link3
        link4 = curent_redirect.link4
        link5 = curent_redirect.link5
        link6 = curent_redirect.link6
        link7 = curent_redirect.link7
        link8 = curent_redirect.link8
        link9 = curent_redirect.link9
        link10 = curent_redirect.link10
        link_list = [link1, link2, link3, link4, link5,
                     link6, link7, link8, link9, link10]
        return render(request, "redirect/redirect.html", context={"links": link_list})
        # return redirect(link1)


def create_link(request):
    if request.method == "POST":
        link1 = request.POST.get('link1')
        link2 = request.POST.get('link2')
        link3 = request.POST.get('link3')
        link4 = request.POST.get('link4')
        link5 = request.POST.get('link5')
        link6 = request.POST.get('link6')
        link7 = request.POST.get('link7')
        link8 = request.POST.get('link8')
        link9 = request.POST.get('link9')
        link10 = request.POST.get('link10')
        r_list = [link1, link2, link3, link4, link5,
                  link6, link7, link8, link9, link10]
        host = request.META['HTTP_HOST']
        l1 = RedirectLink.objects.create(link=link1)
        l1.save()
        l2 = RedirectLink.objects.create(link=link2)
        l2.save()
        l3 = RedirectLink.objects.create(link=link3)
        l3.save()
        l4 = RedirectLink.objects.create(link=link4)
        l4.save()
        l5 = RedirectLink.objects.create(link=link5)
        l5.save()
        l6 = RedirectLink.objects.create(link=link6)
        l6.save()
        l7 = RedirectLink.objects.create(link=link7)
        l7.save()
        l8 = RedirectLink.objects.create(link=link8)
        l8.save()
        l9 = RedirectLink.objects.create(link=link9)
        l9.save()
        l10 = RedirectLink.objects.create(link=link10)
        l10.save()
        now = datetime.now()
        date = int(now.strftime("%d"))
        if date >= 22:
            link1 = l1.get_url2()
            link2 = l2.get_url2()
            link3 = l3.get_url2()
            link4 = l4.get_url2()
            link5 = l5.get_url2()
            link6 = l6.get_url2()
            link7 = l7.get_url2()
            link8 = l8.get_url2()
            link9 = l9.get_url2()
            link10 = l10.get_url2()
            print("ok")
        else:
            # Setting alternative url

            link1 = l1.get_url(request=request)
            link2 = l2.get_url(request=request)
            link3 = l3.get_url(request=request)
            link4 = l4.get_url(request=request)
            link5 = l5.get_url(request=request)
            link6 = l6.get_url(request=request)
            link7 = l7.get_url(request=request)
            link8 = l8.get_url(request=request)
            link9 = l9.get_url(request=request)
            link10 = l10.get_url(request=request)

        # print(r_list)
        # link = f"http://{host}/redirect?link1={link1}&link2={link2}&link3={link3}&link4={link4}&link5={link5}&link6={link6}&link7={link7}&link8={link8}&link9={link9}&link10={link10}"
        new_redirect = Redirect.objects.create(
            link1=link1,
            link2=link2,
            link3=link3,
            link4=link4,
            link5=link5,
            link6=link6,
            link7=link7,
            link8=link8,
            link9=link9,
            link10=link10,

        )
        link = f"""http://{host}/redirect/{new_redirect.unique_id}
        <br>
        Show link - http://{host}/redirect/show/{new_redirect.unique_id}
        """
        return render(request, "redirect/link.html", context={"link1": f"http://{host}/redirect/{new_redirect.unique_id}", "link2": f"http://{host}/redirect/show/{new_redirect.unique_id}"})
        # return HttpResponse(link)


def redirect_link(request, id):
    try:
        url = RedirectLink.objects.get(unique_id=id)
    except (AttributeError, RedirectLink.DoesNotExist):
        raise Http404
    else:
        try:
            return redirect(url.link)
        except NoReverseMatch:
            return render(request, "redirect/close.html")


class ProtectLinkView(View):
    @staticmethod
    def get(request):
        return render(request, "redirect/protect.html")

    @staticmethod
    def post(request):
        link = request.POST['link']
        protected = ProtectLink.objects.create(link=link)
        return HttpResponse(f"""
        
        
         Link - http://{request.META['HTTP_HOST']}/protect/{protected.id}
         <br>
         
         Password - {protected.password}""")


# def see_link(request, id):
#     p_link = ProtectLink.objects.get(id=id)
def showlinks(request, id):
    try:
        curent_redirect = Redirect.objects.get(unique_id=id)
    except Redirect.DoesNotExist:
        raise Http404
    else:
        link1 = curent_redirect.link1
        link2 = curent_redirect.link2
        link3 = curent_redirect.link3
        link4 = curent_redirect.link4
        link5 = curent_redirect.link5
        link6 = curent_redirect.link6
        link7 = curent_redirect.link7
        link8 = curent_redirect.link8
        link9 = curent_redirect.link9
        link10 = curent_redirect.link10
        print(f"link10 - {link10}")
        link_list = [link1, link2, link3, link4, link5,
                     link6, link7, link8, link9, link10]
        return render(request, "redirect/show.html", context={"links": link_list})

templates/redirect/close.html
<script>
window.close();
</script>

templates/redirect/link.html
{% extends 'base2.html' %}
{% block body %}

<script>
function Copy1(){
  var copyText = document.getElementById("link1");
  document.execCommand('copy', "rishit")

}</script>

<a id="link1" href={{link1}} target="_blank" rel="noopener noreferrer">{{link1}}</a>
&nbsp;
<br>
<a id="link2" href={{link2}} target="_blank" rel="noopener noreferrer">{{link2}}</a>

{% endblock body %}

templates/redirect/main.html
{% extends 'base.html' %}
{% block body %}
<h1>10 Link redirect</h1>
<form action="cs" method="post">
{% csrf_token %}
{% for i in '0123456789'|make_list %}
<div class="row g-1 align-items-center">
<div class="col-auto">
<label class="has-text-weight-medium  has-text-centered is-size-5" for="link{{forloop.counter}}">Link {{forloop.counter}}</label>
<input onkeypress="return noenter()"  type="text" placeholder="link{{forloop.counter}}" name="link{{forloop.counter}}" id="link{{forloop.counter}}">
</div>
</div>
</div>
<br>

{% endfor %}

<input type="submit" value="Make link">
</form>
{% endblock body %}

templates/redirect/protect.html
{% extends 'base.html' %}
{% block body %}
<form action="{% url 'redirect:protect' %}" method="post">
{% csrf_token %}
<div class="row g-1 align-items-center">
<div class="col-auto">
<label class="has-text-weight-medium  has-text-centered is-size-5" for="link">Link</label>
<input onkeypress="return noenter()"  type="text" placeholder="link" name="link" id="link" required>
<br><br><br>
<button type="submit">Protect</button>
</div>
</div>
</div>
<br>
</form>
{% endblock body %}

templates/redirect/redirect.html
<script>
document.addEventListener("DOMContentLoaded", () => {
  
      var link1 =document.getElementById("link1")
      window.open(link1.innerHTML, '_blank');
  var link2 =document.getElementById("link2")
      window.open(link2.innerHTML, '_blank');
  var link3 =document.getElementById("link3")
      window.open(link3.innerHTML, '_blank');
      var link4 =document.getElementById("link4")
      window.open(link4.innerHTML, '_blank');
      var link5 =document.getElementById("link5")
      window.open(link5.innerHTML, '_blank');
      var link6 =document.getElementById("link6")
      window.open(link6.innerHTML, '_blank');
      var link7 =document.getElementById("link7")
      window.open(link7.innerHTML, '_blank');
var link8 =document.getElementById("link8")
      window.open(link8.innerHTML, '_blank');
      var link9 =document.getElementById("link9")
      window.open(link9.innerHTML, '_blank');
      var link10 =document.getElementById("link10")
      window.open(link10.innerHTML, '_blank');

})
function clear_q_string(){
    var uri = window.location.toString();
    if (uri.indexOf("?") > 0) {
      var clean_uri = uri.substring(0, uri.indexOf("?"));
      window.history.replaceState({}, document.title, clean_uri);
    }
}
</script>
<h1>Donwloading files</h1>
<div style="display:none;">
{% for link in links %}
<p id="link{{forloop.counter}}">{{link}}</p>
{% endfor %}
</div>

templates/redirect/show.html
{% for link in links %}
<a href={{link}} target="_blank">
{{link}}
</a>
<br>

{% endfor %}